### ISSUE TITLE
ANIMATION GUIDES

### ISSUE THREAD

**Issue by s3arch3** [Dxdiag14/Short-Animation#3]
Hello

1. We will develop by frames, so we have 17 frames in total.
       a. 1 folder under the **frames** tab per scene, there will be 17 folders then + 1 for the intro frame
2. The guides are on the mockups, just find it there :D 
Thank you guys.

**Comment by Sairasu-Kun** [comment]
Yehey

**Comment by s3arch3** [comment]
Yehey

**Comment by s3arch3** [comment]
Comment ka rin ng **yehey** please @Dxdiag14 😢

**Comment by Dxdiag14** [comment]
yehey! ngayon ko lang nakita bruh hehe
